name: Trigger production deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send dispatch event to CICD repository
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CICD_REPO_DISPATCH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ secrets.CICD_REPOSITORY_NAME }}/dispatches \
          --data '{"event_type": "deploy-defi-providers-prod", "client_payload":{"branch": "master"}}'
